# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 15:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[A-Z]{3}\\d{3}')], verbose_name='Course Code')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Credits')),
                ('LTP', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='\\d-\\d-\\d')], verbose_name='LTP')),
                ('contents', models.TextField(verbose_name='Course Contents')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('ptype', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=15, verbose_name='Type')),
                ('department', models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('HU', 'HU')], max_length=50, verbose_name='Department')),
                ('researchInterests', models.TextField(verbose_name='Research Interests')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('ptype', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=15, verbose_name='Type')),
                ('department', models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('HU', 'HU')], max_length=50, verbose_name='Department')),
                ('entryNumber', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Entry Number')),
                ('programmeName', models.CharField(max_length=15, verbose_name='Programme Name')),
                ('hostel', models.CharField(blank=True, max_length=15, verbose_name='Hostel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASE.Faculty'),
        ),
    ]
