# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='instructors', to='ASE.Faculty', verbose_name='Instructors'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='ASE.Faculty', verbose_name='Coordinator'),
        ),
    ]
