# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASE', '0003_auto_20170402_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('advisors', models.ManyToManyField(related_name='advisors', to='ASE.Faculty', verbose_name='Advisors')),
                ('students', models.ManyToManyField(related_name='students', to='ASE.Student', verbose_name='Students')),
            ],
        ),
    ]
