# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ASE', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=10, verbose_name='Status')),
                ('feedback', models.CharField(blank=True, max_length=200, verbose_name='Feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_course', to='ASE.Faculty', verbose_name='Coordinator'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='courses', to='ASE.Faculty', verbose_name='Instructors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='advisors',
            field=models.ManyToManyField(related_name='projects', to='ASE.Faculty', verbose_name='Advisors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='projects', to='ASE.Student', verbose_name='Students'),
        ),
    ]
