# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ASE', '0007_auto_20170426_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=10, verbose_name='Status')),
                ('feedback', models.CharField(blank=True, max_length=200, verbose_name='Feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='request_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ASE.Request'),
            preserve_default=False,
        ),
    ]
