# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASE', '0008_auto_20170426_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ASE.Request')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASE.Course', verbose_name='Data')),
            ],
            bases=('ASE.request',),
        ),
        migrations.CreateModel(
            name='FacultyRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ASE.Request')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASE.Faculty', verbose_name='Data')),
            ],
            bases=('ASE.request',),
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ASE.Request')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASE.Project', verbose_name='Data')),
            ],
            bases=('ASE.request',),
        ),
    ]
