# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASE', '0010_auto_20170426_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10, verbose_name='Status'),
        ),
    ]
