# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASE', '0011_auto_20170426_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
    ]
