# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASE', '0013_auto_20170427_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ASE.Student', verbose_name='Data'),
        ),
    ]
