# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASE', '0014_auto_20170427_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_course', to='ASE.Faculty', verbose_name='Coordinator'),
        ),
    ]
